- name: be sure open-vmtools-repo rpm is installed for RHEL5
  tags: open-vmtools-repo
  copy: src={{ item }} dest=/etc/yum.repos.d/ backup=no
  with_items:
        - VMware-Tools-RHEL5.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5

- name: be sure open-vmtools-repo rpm is installed for RHEL6
  tags: open-vmtools-repo
  copy: src={{ item }} dest=/etc/yum.repos.d/ backup=no
  with_items:
        - VMware-Tools-RHEL6.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6

- name: be sure open-vmtools-repo rpm is installed for RHEL7
  tags: open-vmtools-repo
  copy: src={{ item }} dest=/etc/yum.repos.d/ backup=no
  with_items:
        - VMware-Tools-RHEL7.repo
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7 

- name: yum clean
  shell: yum clean all

- name: be sure vmware-tools-esx-nox is installed
  tags: vmware-tools
  yum: pkg="vmware-tools-esx-nox" state=installed
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6 
  ignore_errors: True

- name: be sure vmware-tools-esx-kmods is installed
  tags: vmware-tools
  yum: pkg="vmware-tools-esx-kmods" state=installed
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 5
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6
  ignore_errors: True

- name: be sure installed rpm rpg-key
  tags: open-vm-tools
  shell: rpm --import http://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub --httpproxy 192.168.1.96 -httpport 8080
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  ignore_errors: True


- name: be sure open-vm-tools is installed
  tags: open-vm-tools
  yum: pkg="open-vm-tools" state=installed
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  ignore_errors: True

- name: be sure vmtoold is enabled
  tags: open-vm-tools
  service: name="vmtoolsd" enabled=yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  ignore_errors: True

- name: vmtoold restart
  tags: open-vm-tools
  service: name="vmtoolsd" state=restarted
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  ignore_errors: True
