- name: test connection (before reboot)
  ping:

#- name: reboot!
#  command: shutdown -r now

- name: reboot after change selinux
  shell: sleep 2s && /sbin/reboot &

- name: wait for SSH port down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for SSH port up
  wait_for: host={{ inventory_hostname }} port=22 state=started delay=30
  delegate_to: 172.16.0.100

- name: test connection (after reboot)
  ping:

