- name: be sure installed rdo-release.rpm
  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-liberty/rdo-release-liberty-1.noarch.rpm state=present

- name: be sure installed openstack-packstack
  yum: name=openstack-packstack

- name: be sure hosts
  template: src={{ item }} dest=/etc/ backup=yes
  with_items:
        - hosts
